# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='latitud_inicial',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='longitud_inicial',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
