# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
