# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='telefono',
        ),
    ]
