# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
