# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='onesignal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
